### ISSUE TITLE
ERROR: ExpansionError during parsing after Poky update

### ISSUE THREAD

**Issue by outbackdingo** [OverC/meta-overc#294]
ERROR: ExpansionError during parsing /var/home/dingo/overc/meta-overc/meta-cube/recipes-support/overc-utils/overc-utils_1.0.bb                  | ETA:  0:00:08
Traceback (most recent call last):
  File "Var <do_fetch[file-checksums]>", line 1, in <module>
  File "/var/home/dingo/overc/poky/bitbake/lib/bb/fetch2/__init__.py", line 1187, in get_checksum_file_list(d=<bb.data_smart.DataSmart object at 0x7f8aab92ea00>):
         """
    >    fetch = Fetch([], d, cache = False, localonly = True)
     
  File "/var/home/dingo/overc/poky/bitbake/lib/bb/fetch2/__init__.py", line 1638, in Fetch.__init__(urls=['file://source/cube-cmd', 'file://source/c3-cap', 'file://source/cube-ctl', 'file://source/cube-cfg', 'file://source/nctl', 'file://source/cube', 'file://source/cube-console', 'file://source/COPYING', 'file://source/cube-device', 'file://source/13-cube-device.rules', 'file://source/cube-device.sh', 'file://source/cube-device-functions', 'file://source/c3-completions', 'file://source/c3-construct', 'file://source/c3-cmds/*'], d=<bb.data_smart.DataSmart object at 0x7f8aab92ea00>, cache=False, localonly=True, connection_cache=None):
                     try:
    >                    self.ud[url] = FetchData(url, d, localonly)
                     except NonLocalMethod:
  File "/var/home/dingo/overc/poky/bitbake/lib/bb/fetch2/__init__.py", line 1282, in FetchData.__init__(url='file://source/c3-cmds/*', d=<bb.data_smart.DataSmart object at 0x7f8aab92ea00>, localonly=True):
             if hasattr(self.method, "urldata_init"):
    >            self.method.urldata_init(self, d)
     
  File "/var/home/dingo/overc/poky/bitbake/lib/bb/fetch2/local.py", line 37, in Local.urldata_init(ud=<bb.fetch2.FetchData object at 0x7f8aae0eae50>, d=<bb.data_smart.DataSmart object at 0x7f8aab92ea00>):
             if "*" in ud.decodedurl:
    >            raise bb.fetch2.ParameterError("file:// urls using globbing are no longer supported. Please place the files in a directory and reference that instead.", ud.url)
             return
bb.data_smart.ExpansionError: Failure expanding variable do_fetch[file-checksums], expression was ${@bb.fetch.get_checksum_file_list(d)}  ${@get_lic_checksum_file_list(d)} which triggered exception ParameterError: URL: 'file://source/c3-cmds/*' has invalid parameters. file:// urls using globbing are no longer supported. Please place the files in a directory and reference that instead.

Summary: There was 1 WARNING message shown.
Summary: There was 1 ERROR message shown, returning a non-zero exit code.

**Comment by zeddii** [comment]
I was expecting this one :D The fix will be in place shortly.

**Comment by outbackdingo** [comment]
seems fixed
